# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb-zi
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    ports:
     - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express-zi
    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${UI_BASIC_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${UI_BASIC_PASSWORD}"
