# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb-zi
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-username-here
      MONGO_INITDB_ROOT_PASSWORD: mongoPasswordHere
    ports:
     - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express-zi
    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-username-here
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoPasswordHere
      ME_CONFIG_BASICAUTH_USERNAME: mongo-express-username-here
      ME_CONFIG_BASICAUTH_PASSWORD: mongoExpressPasswordHere
